- prefix: /app1/service-a
  headers:
    - App-Stack: 1
    - App-Name: app1
  cluster: app1-service-a-0-0-30

- prefix: /app1/service-a
  headers:
    - App-Stack: 2
    - App-Name: app1
  cluster: app1-service-a-0-0-30

- prefix: /app1/service-b
  headers:
    - App-Stack: 1
    - App-Name: app1
  cluster: app1-service-b-0-0-4

- prefix: /app1/service-b
  headers:
    - App-Stack: 2
    - App-Name: app1
  cluster: app1-service-b-0-0-5

- prefix: /app2/service-y
  headers:
    - App-Stack: 1
    - App-Name: app1
  cluster: app2-service-s-0-0-2

- prefix: /app2/service-y
  headers:
  headers:
    - App-Stack: 2
    - App-Name: app1
  cluster: app2-service-s-0-0-2

- prefix: /shared/service-s
  headers:
    - App-Stack: 1
    - App-Name: app1
  cluster: shared-service-s-0-0-1

- prefix: /shared/service-s
  headers:
    - App-Stack: 1
    - App-Name: app2
  cluster: shared-app-service-s-0-0-1

- prefix: /shared/service-s
  headers:
    - App-Stack: 2
    - App-Name: app2
  cluster: shared-app-service-s-0-0-1

- prefix: /shared/service-s
  headers:
    - App-Stack: 2
    - App-Name: app1
  cluster: shared-app-service-s-0-0-2